- hosts: all
  remote_user: gaith
  gather_facts: no
  become: yes
  vars:
    allow_world_readable_tmpfiles: true
  vars_files:
    - vars/all.yml
    - vars/user.yml
    - vars/hadoop.yml
    - vars/postgres.yml
  roles:
    - common

