---

- name: test
  debug:
    msg: "YO"

- name: Add User 
  user: name={{user}} shell=/bin/bash append=yes

- name: Check Public Key
  shell: "ls /home/{{ user }}/.ssh|grep '.pub' |wc -l"
  register: key_exist
  ignore_errors: true

- name: Generate Public key
  user:
    name: "{{ user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: "key_exist.stdout == '0'"

- name: Add user to sudoers and enable passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ user }}  ALL=(ALL) NOPASSWD:ALL'
    line: '{{ user }}  ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

- name: Get Lastest Public From Hadoop Master
  fetch: 
    src: /home/{{ user }}/.ssh/id_rsa.pub
    dest: /tmp/id_{{ ansible_host }}_{{ user }}.pub
    flat: yes

- name: Add Cluster Public Key for Hadoop
  authorized_key: 
    user={{ user }} 
    key="{{ lookup('file', '/tmp/id_{{master_ip}}_{{user}}.pub') }}"

- name: Add User Public Key for Hadoop
  authorized_key: 
    user={{ user }} 
    key="{{ user_ssh_key }}"

